version:  '3'

services:
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      -  '9000:9000'
      -  '9001:9001'
    networks:
      -  minio_network
    volumes:
      - minio_db:/volumes/data/minio
    environment:
      -  MINIO_ROOT_USER=user
      -  MINIO_ROOT_PASSWORD=12345678
      -  MINIO_DEFAULT_BUCKETS=miniobucket

networks:
  minio_network:
    driver:  bridge

volumes:
  minio_db:
    driver: local